weather_dbt:
  target: staging
  outputs:
    staging:
      type: snowflake
      account: "{{ env_var('STAGING_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('STAGING_SNOWFLAKE_USER') }}"
      password: "{{ env_var('STAGING_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('STAGING_SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('STAGING_SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('STAGING_SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('STAGING_SNOWFLAKE_SCHEMA') }}"
      threads: 1
      client_session_keep_alive: False
    production:
      type: snowflake
      account: "{{ env_var('PRODUCTION_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('PRODUCTION_SNOWFLAKE_USER') }}"
      password: "{{ env_var('PRODUCTION_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('PRODUCTION_SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('PRODUCTION_SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('PRODUCTION_SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('PRODUCTION_SNOWFLAKE_SCHEMA') }}"
      threads: 1
      client_session_keep_alive: False
