#FROM apache/airflow:slim-3.0.3-python3.12
FROM apache/airflow:2.9.1-python3.10

# Install extra Python dependencies
RUN pip install --no-cache-dir meteomatics snowflake-connector-python pandas dbt-snowflake
